forum/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.ThreadCategoryListView.as_view(), name='forum'),

    url(r'^add_category/$',
        views.AddThreadCategoryView.as_view(), name='add_thread_category'),

    url(r'^category/(?P<slug>[\w-]+)/$',
        views.thread_category_detail, name='detail_thread_category'),

    url(r'^category/(?P<slug>[\w-]+)/edit/(?P<pk>\d+)/$',
        views.thread_category_detail, name='detail_thread_category_edit_thread'),

    url(r'^category/(?P<category_slug>[\w-]+)/thread/(?P<slug>[\w-]+)/$',
        views.thread_detail, name='detail_thread'),

    url(r'^category/(?P<category_slug>[\w-]+)/thread/(?P<slug>[\w-]+)/edit/(?P<pk>\d+)/$',
        views.thread_detail, name='detail_thread_edit_post'),
]

webraid/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import settings
import profiles.urls
import forum.urls
<<<<<<< HEAD

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include(forum.urls)),
    url(r'^', include(profiles.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
=======
import notifications.urls
import utils.urls

urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^forum/', include(forum.urls)),
                  url(r'^notifications/', include(notifications.urls)),
                  url(r'^u/', include(utils.urls)),
                  url(r'^', include(profiles.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
>>>>>>> 9350566dfec21f0cd1aad032f264d82b996d8fba

forum/models.py
from django.core.urlresolvers import reverse
from django.db import models

from notifications.utils import NotificationContentProviderMixin, NotificationParentMixin
from profiles.models import UserProfile
from utils.models import Tag
from utils.snippets.slugifiers import unique_slugify



# Create your models here.

class ThreadCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(max_length=50,
                            unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum.views.thread_category_detail', args=[self.slug])

    def save(self, **kwargs):
        unique_slugify(self, self.name)
        super(ThreadCategory, self).save(**kwargs)


class Thread(models.Model):
    category = models.ForeignKey(ThreadCategory)
    title = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(max_length=50,
                            unique=True)
    creation_date = models.DateField(
        verbose_name="Thread creation date",
        auto_created=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        slug_category = self.category.slug
        return reverse('forum.views.thread_detail', args=[slug_category, self.slug])

    def save(self, **kwargs):
        unique_slugify(self, self.title)
        super(Thread, self).save(**kwargs)

    def delete_with_posts(self):
        for post in Post.objects.filter(thread=self):
            post.delete()
        self.delete()

    def get_content(self):
        return unicode(self.category.__str__() + "/" + self.title)

    def get_parent_context(self):
        return {
            'name': self.title,
            'url': self.get_absolute_url()
        }

    # Get the list of tagged users : all the users tagged in posts + authors
    def get_tagged_users(self):
        tagged_users = []
        for post in Post.objects.filter(thread=self):
            tagged_users.append(post.author)
            for usp in UserTag.objects.filter(post=post):
                tagged_users.append(usp.user_profile)
        res = []
        for user in list(set(tagged_users)):
            res.append((user, tagged_users.count(user)))
        return res

    def get_last_posts(self, limit=10):
        return Post.objects.filter(thread=self).order_by('-posted_date')[:limit]


    @staticmethod
    def get_last_threads_posted_in(limit=1):
        thread_with_last_posted_date = []
        for thread in Thread.objects.all():
            last_post = Post.objects.filter(thread=thread).order_by('-posted_date')[:1]
            if last_post is not None:
                thread_with_last_posted_date.append(
                        {
                            'thread': thread,
                            'last_posted_date': last_post[0].posted_date
                        }
                )
        thread_with_last_posted_date.sort(key=lambda x: x['last_posted_date'], reverse=True)
        return thread_with_last_posted_date[:limit]

    @staticmethod
    def get_last_threads_posted_in_with_posts(threads_limit=1, posts_limit=1):
        thread_with_last_posted_date = []
        for thread in Thread.objects.all():
            last_posts = Post.objects.filter(thread=thread).order_by('-posted_date')
            lp_len = last_posts.__len__()
            if (last_posts is not None) and (lp_len > 0):
                thread_with_last_posted_date.append(
                    {
                        'thread': thread,
                        'last_posted_date': last_posts[1].posted_date,
                        'first_posts': last_posts[(lp_len - posts_limit):lp_len]
                    }
                )
        thread_with_last_posted_date.sort(key=lambda x: x['last_posted_date'], reverse=True)
        return thread_with_last_posted_date[:threads_limit]


class Post(models.Model):
    thread = models.ForeignKey(Thread)
    # Contenu
    text_content = models.TextField()
    author = models.ForeignKey(UserProfile)
    posted_date = models.DateTimeField(auto_now_add=True)
    last_edit_date = models.DateTimeField(auto_now=True)
    # File uploads
    file = models.FileField()

    def get_absolute_url(self):
        return self.thread.get_absolute_url() + "#post-" + str(self.id)

    def save(self, **kwargs):
        super(Post, self).save(**kwargs)
        # Add UserTags
        for user in UserProfile.auto_tag(self.text_content):
            user_profile = UserProfile.objects.get(user=user)
            UserTag(user_profile=user_profile, post=self).save()
        # Save tags
        for tag in Tag.extract(self.text_content):
            PostTag(post=self, tag=tag).save()

    # What we send as the new object's content for sending notifications
    def get_content(self):
        return unicode(self.text_content)

    @staticmethod
    def get_last_posts_by_author_with_answers(user, posts_limit=1, answers_limit=0):
        post_and_answers = []
        posts_retrieved = 0
        for thread in Thread.objects.all():
            for post in Post.objects.filter(thread=thread, author=user.user_profile).order_by('-posted_date')[:1]:
                answers = Post.objects \
                              .filter(thread=post.thread).exclude(author=user.user_profile) \
                              .filter(posted_date__gte=post.posted_date).order_by('posted_date')[:answers_limit]
                post_and_answers.append({'date': post.posted_date, 'post': post, 'answers': answers})
                posts_retrieved += 1
                if posts_limit == posts_retrieved:
                    post_and_answers.sort(key=lambda x: x['date'], reverse=True)
                    return post_and_answers

        post_and_answers.sort(key=lambda x: x['date'], reverse=True)
        return post_and_answers

    @staticmethod
    def get_last_posts(last_posts_no=1):
        return Post.objects.all().order_by('-posted_date')[:last_posts_no]


class UserTag(models.Model, NotificationContentProviderMixin):
    post = models.ForeignKey(Post)
    user_profile = models.ForeignKey(UserProfile)

    def get_content(self):
        return unicode(self.user_profile.__str__())


class PostTag(models.Model):
    post = models.ForeignKey(Post)
    tag = models.ForeignKey(Tag)

forum/forms.py
from django import forms

from models import ThreadCategory, Thread, Post
from utils.models import Tag


class ThreadCategoryForm(forms.ModelForm):
    description = forms.CharField(required=False,
                                  widget=forms.Textarea)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          required=False)

    class Meta:
        model = ThreadCategory
        fields = (
            'name',
            'description',
            'tags'
        )


class ThreadForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          required=False)

    class Meta:
        model = Thread
        fields = (
            'title',
            'tags'
        )


class PostForm(forms.ModelForm):
    file = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = (
            'text_content',
            'file'
        )

forum/views.py
from django.views.generic import ListView, FormView
from django.http import Http404
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render

from profiles.models import UserProfile
from models import ThreadCategory, Thread, Post, UserTag, PostTag
from forms import ThreadCategoryForm, ThreadForm, PostForm


class ThreadCategoryListView(ListView):
    model = ThreadCategory
    template_name = "forum.html"


class AddThreadCategoryView(FormView):
    template_name = 'forms/thread_category_form.html'
    form_class = ThreadCategoryForm
    success_url = '/forum/'

    def form_valid(self, form):
        form.save()
        return super(AddThreadCategoryView, self).form_valid(form)


def thread_category_detail(request, slug, pk=None):
    if pk is not None:
        edit_thread = Thread.objects.get(pk=pk)
    else:
        edit_thread = None

    try:
        thread_category = ThreadCategory.objects.get(slug=slug)
        thread_list = Thread.objects.filter(category=thread_category.pk)
    except ThreadCategory.DoesNotExist:
        raise Http404("Thread category does not exist!")

    data = {
        'thread_category': thread_category,
        'thread_list': thread_list,
        'form': ThreadForm(),
        'slug': slug,
    }

    if request.method == 'POST':
        if 'new-thread' in request.POST:
            form = ThreadForm(request.POST)
            if form.is_valid():
                thread = form.save(commit=False)
                thread.category = thread_category
                thread.save()

                return redirect(thread_category.get_absolute_url())
            else:
                data.update({'form': form})
                return render(request,
                              'thread_category.html',
                              data)

        elif 'edit-thread' in request.POST:
            edit_thread_form = ThreadForm(request.POST, instance=edit_thread)
            if edit_thread_form.is_valid():
                edit_thread_form.save()

                return redirect(thread_category.get_absolute_url())
            else:
                data.update({
                    'pk': edit_thread.pk,
                    'edit_thread_form': edit_thread_form,
                })
                return render(request,
                              'thread_category.html',
                              data)

    if edit_thread is not None:
        edit_thread_form = ThreadForm(instance=edit_thread)

        data['pk'] = edit_thread.pk
        data['edit_thread_form'] = edit_thread_form
        data['edit_thread'] = edit_thread

    return render(request, 'thread_category.html', data)


def thread_detail(request, category_slug, slug, pk=None):
    if pk is not None:
        edit_post = Post.objects.get(pk=pk)
        if edit_post.author.user != request.user:
            raise PermissionDenied
    else:
        edit_post = None

    try:
        thread = Thread.objects.get(slug=slug)
        post_list = Post.objects.filter(thread=thread.pk)
    except Thread.DoesNotExist:
        raise Http404("Thread does not exist!")

    if request.method == 'POST':

        if 'edit-post' in request.POST:
            edit_post_form = PostForm(request.POST, instance=edit_post)

            if edit_post_form.is_valid():
                edit_post_form.save()
                return redirect(thread.get_absolute_url())
            else:
                return render(request,
                              'thread.html',
                              {
                                  'thread': thread,
                                  'post_list': post_list,
                                  'edit_post_form': edit_post_form,
                                  'category_slug': category_slug,
                                  'slug': slug,
                                  'pk': edit_post.pk,
                                  'edit_post': edit_post,
                              })

        elif 'new-post' in request.POST:
            form = PostForm(request.POST)

            if form.is_valid():
                post = form.save(commit=False)
                post.author = UserProfile.objects.get(user=request.user)
                post.thread = thread
                post.save()

                return redirect(thread.get_absolute_url())
            else:
                return render(request,
                              'thread.html',
                              {
                                  'thread': thread,
                                  'post_list': post_list,
                                  'form': form,
                                  'slug': slug,
                                  'category_slug': category_slug,
                                  'edit_post': edit_post,
                              })
    data = {
        'thread': thread,
        'post_list': post_list,
        'form': PostForm(),
        'slug': slug,
        'category_slug': category_slug,
    }

    if edit_post is not None:
        edit_post_form = PostForm(instance=edit_post)
        data['edit_post_form'] = edit_post_form
        data['pk'] = edit_post.pk
        data['edit_post'] = edit_post
        return render(request, 'thread.html', data)
    else:
        return render(request, 'thread.html', data)

def thread_delete(request, slug):
    if request.user.is_superuser:
        thread = Thread.objects.get(slug=slug)
        thread.delete_with_posts()
    return redirect(request.META.get('HTTP_REFERER'))


def category_delete(request, slug):
    if request.user.is_superuser:
        category = ThreadCategory.objects.get(slug=slug)
        category.delete_recursive()
    return redirect(request.META.get('HTTP_REFERER'))


def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    parent = post.thread
    if request.user == post.author.user:
        post.delete()
        UserTag.objects.filter(post=post).delete()
        PostTag.objects.filter(post=post).delete()

    else:
        raise PermissionDenied

    return redirect(parent.get_absolute_url())

templates/forum/forum.html
{% extends 'base.html' %}
{% load bootstrapify %}
{% load utils_filters %}
{% block path %}
    forum /
{% endblock %}
{% block content %}
    <div class="row">
        {% for threadCategory in threadcategory_list %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card white">
                    <div hidden class="panel-actions">
                        {% if request.user.is_superuser %}
                            <a class="action" href="{% url 'delete_category' threadCategory.slug %}"><i
                                    class="fa fa-fw fa-trash"></i></a>
                        {% endif %}
                        <!--<a href="{% url 'follow_category' threadCategory.slug %}">Suivre</a>-->
                    </div>
                    <a href="{{ threadCategory.get_absolute_url }}">
                        <div class="card-title">
                            {{ threadCategory.name }}
                        </div>
                    </a>

                    <div class="card-summary">
                        {{ threadCategory.description }}
                        {{ threadCategory.tags.all | displaytags }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <a class="btn btn-default" href="{% url 'add_thread_category' %}">
        <i class="fa fa-fw fa-plus-circle"></i> Ajouter un thème
    </a>
{% endblock %}

templates/forum/thread.html
{% extends 'base.html' %}
{% load bootstrapify %}
<<<<<<< HEAD
=======
{% load staticfiles %}
{% load helper_tags %}
{% load prettify %}
{% block extrahead %}
    <script src="{% static 'js/customformats.js' %}" type="text/javascript"></script>
{% endblock %}

{% block path %}
    <a href="{% url 'forum' %}">forum</a> /
    {% pretty_thread_path thread %}
{% endblock %}

>>>>>>> 9350566dfec21f0cd1aad032f264d82b996d8fba
{% block content %}
    <h2><a href="{% url 'detail_thread_category' thread.category.slug %}">{{ thread.title | fa_return }}</a></h2>
    <p>
        {% for post in post_list %}
<<<<<<< HEAD
            <div class="panel">
                {% if post == edit_post %}
                    <form method="POST" action="{% url 'detail_thread_edit_post' category_slug slug edit_post.pk %}">
                        {% csrf_token %}
                        <div class="body">
                            {{ edit_post_form.text_content | bs_form_input:"" }}
                            {{ edit_post_form.file }}
=======
            <li class="post-container">
                <div itemscope itemtype="http://schema.org/DiscussionForumPosting"
                     class="panel--post {% if user == post.author.user %}self{% else %}other{% endif %}"
                     id="post-{{ post.id }}"
                >
                    <span hidden class="username" itemprop="author">{{ post.author.user.username }}</span>
                    {% if post == edit_post %}
                        <form id="post-edit-form"
                              method="POST"
                              action="{% url 'detail_thread_edit_post' category_slug slug edit_post.pk %}"
                        >
                            {% csrf_token %}
                            <div class="panel-body--post">
                                {{ edit_post_form.text_content | bs_form_input:"" }}
                                {{ edit_post_form.file }}
                            </div>
                            <div class="panel-footer--post">
                                <input type="submit" class="btn btn-default" value="Valider" name="edit-post">
                            </div>
                        </form>
                    {% else %}
                        {% if user != post.author.user %}
                            <div class="panel-title--post">
                                {{ post.author.user.first_name }} {{ post.author.user.last_name }}
                            </div>
                        {% endif %}
                        <div class="panel-body--post">
                            <p>{{ post.text_content }}</p>
>>>>>>> 9350566dfec21f0cd1aad032f264d82b996d8fba
                        </div>
                        <div class="panel-footer">
                            <input type="submit" class="btn btn-default" value="Valider" name="edit-post">
                        </div>
                    </form>
                {% else %}

                    <div class="panel-body">
                        {{ post.text_content }}
                    </div>
                    <div class="panel-footer">
                        {{ post.author }}
                        Posted on {{ post.posted_date | date }},
                        last edited on {{ post.last_edit_date | date }}
                        {% if user == post.author.user %}
                            <a href="{% url 'detail_thread_edit_post' category_slug slug post.pk %}">edit</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </p>
    <p>
<<<<<<< HEAD
    <form method="POST" action="{% url 'detail_thread' category_slug slug %}">
        {% csrf_token %}
        {{ form.text_content | bs_form_input:"" }}
        {{ form.file }}
        <input type="submit" class="btn btn-default" value="Poster" name="new-post">
    </form>
=======
    <div class="panel--post new" id="new-post-form">
        <form method="POST" action="{% url 'detail_thread' category_slug slug %}">
            {% csrf_token %}
            <div class="well-sm">
                {{ form.text_content | bs_form_input:"" }}
                {{ form.file | bs_file_input }}
            </div>
            <input type="submit" class="btn btn-default" value="Poster" name="new-post">
        </form>
    </div>
>>>>>>> 9350566dfec21f0cd1aad032f264d82b996d8fba
    </p>
    <!-- Scroll-up -->
    <div class="scroll-up">
        <ul>
            <li><a href="#header"><i class="fa fa-angle-up"></i></a></li>
        </ul>
    </div>
<<<<<<< HEAD
=======
{% endblock %}

{% block extrajs %}
    <script src="{% static 'js/linkify.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/linkify-jquery.min.js' %}" type="text/javascript"></script>
    <script>$('p').linkify();</script>
    {% init_fuzzy_search "content" "'username'" %}
    <!-- Enable tagging users with @ -->
    <script>
        $('textarea').triggeredAutocomplete({
                    hidden: '#hidden_inputbox',
                    source: '/users_json',
                    trigger: '@',
                    maxLength: 30
                }
        );
    </script>
>>>>>>> 9350566dfec21f0cd1aad032f264d82b996d8fba
{% endblock %}

templates/forum/thread_category.html
{% extends 'base.html' %}
{% load bootstrapify %}
{% load utils_filters %}
{% load helper_tags %}
{% load prettify %}
{% block path %}
    <a href="{% url 'forum' %}">forum</a> /
    {{ thread_category.name }}
{% endblock %}
{% block content %}
    <div class="row">
        {% for thread, following in thread_list.items %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="panel">
                    {% if thread == edit_thread %}
                        <form action="{% url 'detail_thread_category_edit_thread' slug edit_thread.pk %}"
                              method="POST"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="panel-heading bookface">
                                {{ edit_thread_form.title | bs_form_input }}
                            </div>
                            <div class="panel-body">
                                {{ edit_thread_form.tags | bs_form_input_h:"Tags" }}
                            </div>
                            <div class="panel-footer">
                                <input type="submit" class="btn btn-default" value="Valider" name="edit-thread">
                            </div>
                        </form>
                    {% else %}
                        <div class="panel-actions">
                            {% if request.user.is_superuser %}
                                <a class="action" href="{% url 'delete_thread' thread.slug %}"><i
                                        class="fa fa-fw fa-trash"></i></a>
                            {% endif %}
                            {% if not following %}
                                <a class="action" href="{% url 'follow_thread' thread.slug %}">
                                    <i class="fa fa-fw fa-eye"></i> Suivre
                                </a>
                            {% else %}
                                <a class="action" href="{% url 'unfollow_thread' thread.slug %}">
                                    <i class="fa fa-fw fa-eye-slash"></i> Ne plus suivre
                                </a>
                            {% endif %}
                        </div>
                        <a class="panel-heading active" href="{{ thread.get_absolute_url }}">
                            <span class="bookface">{{ thread.title }}</span>
                            {% if following %}
                                <span class="tag tag-green"> abonné
                                    <span class="info"><i class="fa fa-fw fa-eye"></i></span>
                                </span>
                            {% endif %}
                        </a>
                        <div class="panel-body">
                            {% if thread.tags != None and thread.tags.count > 0 %}
                                Tags : {% for tag in thread.tags.all %}{% pretty_tag tag %}{% endfor %} <br/>
                                Utilisateurs :
                                {% for usr, count in thread.get_tagged_users %}
                                    {% pretty_user_tag usr count %}
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="panel-footer">
                            <a class="btn-sm" href="{% url 'detail_thread_category_edit_thread' slug thread.pk %}">
                                <i class="fa fa-edit"></i> modifier
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="panel">
        <div class="panel-heading">
            <span class="title"><i class="fa fa-fw fa-plus-circle"></i> Ajouter un fil de discussion</span>
        </div>
        <div class="panel-body">
            <form action="{% url 'detail_thread_category' slug %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.title | bs_form_input_h:"Titre du fil de discussion" }}
                {{ form.tags | bs_form_input_h:"Tags" }}
                <input type="submit" class="btn btn-default" value="Nouvelle discussion" name="new-thread">
            </form>
        </div>
    </div>
{% endblock %}